branches:
  except: /^v\d/
language: node_js
node_js: node
matrix:
  include:
  - after_script: node_modules/.bin/nyc report --reporter=text-lcov | npx coveralls
  - os: windows
    script: node test.js
