shallow_clone: true
version: '{build}'
skip_tags: true
install:
  - ps: Install-Product node Stable
  - npm uninstall --save-dev @shinnn/eslint-config-node eslint
  - npm install
build: off
test_script: node --strong_mode test.js
cache: node_modules -> package.json
